// AUTO-GENERATED by export_weights.py  do not edit.
// ---------------------------------------------------------------------------
// FIX (2026-05-31): the original emitted `define ENDIF at the bottom instead of
// the include-guard's closing `endif. An unterminated `ifndef is illegal and
// breaks the preprocessor / synthesis. The closing directive is corrected below.
// REMEMBER to also fix export_weights.py so it emits `endif (not `define ENDIF).
// ---------------------------------------------------------------------------
`ifndef NN_PARAMS_AUTO_SVH
`define NN_PARAMS_AUTO_SVH

`define NN_INPUT_SIZE   784
`define NN_HIDDEN1_SIZE 128
`define NN_HIDDEN2_SIZE 64
`define NN_OUTPUT_SIZE  10
`define NN_FRAC_BITS    16
`define NN_L0_MQ        32'h00000015
`define NN_L1_M_Q        32'h00000098
`define NN_L2_MQ        32'h0000008d

`endif // NN_PARAMS_AUTO_SVH